version: "3.9"

services:
  barber_calendar:
    build: .
    container_name: barber_calendar_app
    restart: unless-stopped
    environment:
      - SECRET_KEY=${SECRET_KEY:-dev_secret}
      - DATABASE_URL=sqlite:///instance/agenda.db
      - FLASK_ENV=production
    volumes:
      # Mapeia a pasta instance para não perder o banco de dados e agendamentos
      - ./instance:/app/instance
    ports:
      - "127.0.0.1:8000:8000"

