BEGIN;
CREATE TABLE IF NOT EXISTS users (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password_hash TEXT NOT NULL,
  role TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS availability (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  day INTEGER NOT NULL,
  time TEXT NOT NULL,
  active INTEGER DEFAULT 1
);
CREATE TABLE IF NOT EXISTS bookings (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  user_id INTEGER NOT NULL,
  day INTEGER NOT NULL,
  month INTEGER,
  year INTEGER,
  time TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'confirmado',
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  service TEXT DEFAULT 'corte de cabelo',
  FOREIGN KEY(user_id) REFERENCES users(id)
);
COMMIT;
